apiVersion: v1
kind: ConfigMap
metadata:
    name: production-php-fpm
data:
    www.conf: |
        ; The below default configuration is based on a server without much resources.
        ; Don't forget to tweak it to fit expected workload and hardware.
        ;
        ; https://www.php.net/manual/en/install.fpm.configuration.php
        [www]

        user = www-data
        group = www-data

        listen = 127.0.0.1:9000

        pm = static
        pm.max_children = 8
        pm.max_requests = 1000

        access.log = /dev/null
