apiVersion: v1
kind: ConfigMap
metadata:
    name: redis
data:
    redis.conf: |
        tcp-keepalive 30
        timeout 60
        loglevel notice
        maxmemory 2200mb
        maxmemory-policy volatile-lru
