apiVersion: v1
kind: ConfigMap
metadata:
    name: redis
data:
    redis.conf: |
        tcp-keepalive 30
        timeout 60
        loglevel notice
        maxmemory 2200mb
        maxmemory-policy volatile-lru
        
        # Disable AOF and RDB persistence as we keep everything in memory only, see https://redis.io/topics/persistence
        appendonly no
        # Disable RDB persistence, AOF persistence already disabled above.
        save ""
        
        # Enabling active memory defragmentation
        activedefrag yes
