apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: webserver-php-fpm
    namespace: "{{PROJECT_NAME}}"
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: webserver-php-fpm
    minReplicas: 2
    maxReplicas: 2
    metrics:
        -   type: ContainerResource
            containerResource:
                name: cpu
                container: php-fpm
                target:
                    type: Utilization
                    averageUtilization: 80
