apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: webserver-php-fpm
    namespace: "{{PROJECT_NAME}}"
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: webserver-php-fpm
    minReplicas: 2
    maxReplicas: 2
    metrics:
        -   type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization
                    averageUtilization: 75
