apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            annotations:
                logging/enabled: "false"
                project/app: "redis"
                project/environment: "{{PROJECT_ENVIRONMENT}}"
                project/name: "{{NAME_OF_PROJECT}}"
            labels:
                app: redis
        spec:
            volumes:
                -   name: health
                    configMap:
                        name: redis-health-configmap
                        defaultMode: 0755
                -   name: config
                    configMap:
                        name: redis
                        defaultMode: 0755
            containers:
                -   name: redis-exporter
                    image: "oliver006/redis_exporter"
                    imagePullPolicy: Always
                    ports:
                        -   name: prometheus-exporter
                            containerPort: 9121
                            protocol: TCP
                    resources:
                        limits:
                            cpu: 100m
                            memory: 128Mi
                        requests:
                            cpu: 100m
                            memory: 128Mi
                -   name: redis
                    image: "{{REDIS_VERSION}}"
                    ports:
                        -   name: redis
                            containerPort: 6379
                            protocol: TCP
                    volumeMounts:
                        -   name: health
                            mountPath: /health
                        -   name: config
                            mountPath: /usr/local/etc/redis/redis.conf
                            subPath: redis.conf
                    args:
                        - /usr/local/etc/redis/redis.conf
                    livenessProbe:
                        initialDelaySeconds: 30
                        timeoutSeconds: 5
                        exec:
                            command:
                                - sh
                                - -c
                                - /health/liveness.sh 5
                    readinessProbe:
                        initialDelaySeconds: 5
                        timeoutSeconds: 5
                        exec:
                            command:
                                - sh
                                - -c
                                - /health/readiness.sh 5
                    resources:
                        limits:
                            memory: "2500Mi"
                            cpu: "1"
                        requests:
                            memory: "250Mi"
                            cpu: "0.1"
