apiVersion: apps/v1
kind: Deployment
metadata:
    name: storefront
spec:
    replicas: 1
    selector:
        matchLabels:
            app: storefront
    template:
        metadata:
            annotations:
                logging/enabled: "false"
                project/app: "storefront"
                project/environment: "{{PROJECT_ENVIRONMENT}}"
                project/name: "{{NAME_OF_PROJECT}}"
            labels:
                app: storefront
        spec:
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        -   weight: 100
                            podAffinityTerm:
                                topologyKey: "kubernetes.io/hostname"
                                labelSelector:
                                    matchExpressions:
                                        -   key: app
                                            operator: In
                                            values:
                                                - storefront
            containers:
                -   name: storefront
                    image: "{{STOREFRONT_TAG}}"
                    ports:
                        -   name: storefront
                            containerPort: 3000
                            protocol: TCP
                    lifecycle:
                        preStop:
                            exec:
                                command:
                                    - sleep
                                    - '10'
                    resources:
                        limits:
                            cpu: "1.5"
                            memory: "1.5Gi"
                        requests:
                            cpu: "1"
                            memory: "800Mi"
                    livenessProbe:
                        httpGet:
                            path: /api/health
                            port: 3000
                        initialDelaySeconds: 30
                        periodSeconds: 5
                        timeoutSeconds: 5
                    readinessProbe:
                        httpGet:
                            path: /api/health
                            port: 3000
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        timeoutSeconds: 5
            terminationGracePeriodSeconds: 60
            imagePullSecrets:
                -   name: dockerregistry
