apiVersion: v1
kind: Service
metadata:
    name: gotenberg
    labels:
        app: gotenberg
spec:
    selector:
        app: gotenberg
    ports:
        -   name: http
            port: 3000
            targetPort: 3000
