apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
    labels:
        prometheus-exporter: true
spec:
    selector:
        app: rabbitmq
    ports:
        -   name: rabbitmq
            port: 5672
            targetPort: 5672
        -   name: rabbitmq-management
            port: 15672
            targetPort: 15672
        -   name: prometheus-exporter
            port: 15692
            targetPort: 15692
